version: 2

models:
  - name: dashboard_metrics
    description: "Dashboard-optimized metrics with one row per city/place_type combination"
    columns:
      - name: city
        description: "City name (Helsinki, Stockholm, Copenhagen, Berlin, London, Amsterdam)"
      - name: place_type
        description: "Type of place: cafe or restaurant"
      - name: ingestion_timestamp
        description: "When the data was processed (nanoseconds since epoch)"
      - name: total_count
        description: "Total number of places found"
      - name: excellent_count
        description: "Number of excellent places (4.5+ rating)"
      - name: excellence_percentage
        description: "Percentage of places that are excellent (4.5+ rating)"
      - name: readable_timestamp
        description: "Human-readable timestamp for dashboard display"
      - name: place_type_display
        description: "Formatted place type for dashboard display (Cafes, Restaurants)"
      - name: excellence_rank
        description: "Ranking by excellence percentage within each place type"


