version: 2

sources:
  - name: raw_maps
    description: Raw Google Maps API data from BigQuery
    tables:
      - name: raw_maps_data
        description: Raw geocoding results from Google Maps API
        columns:
          - name: timestamp
            description: When the API call was made
          - name: query
            description: Original search query
          - name: place_data
            description: Structured place information from Maps API
          - name: api_status
            description: API response status (OK, ZERO_RESULTS, etc.)