version: 2

sources:
  - name: maps_data
    description: Raw Maps API data from BigQuery
    tables:
      - name: raw_maps_data
        description: Raw ingested Maps API responses
        columns:
          - name: ingestion_timestamp
            description: When the data was processed (nanoseconds since epoch)
          - name: city
            description: City name
          - name: place_type
            description: Type of place (cafe or restaurant)
          - name: rating_filter
            description: Rating filter applied (NULL or 4.5)
          - name: count
            description: Number of places found